imports:
- path: twitter-aggregator.jinja
  name: twitter-aggregator.jinja

resources:
- name: twitter-aggregator
  type: twitter-aggregator.jinja
  properties:
    description: "Twitter aggregator"
    project-name: YOUR_VALUE
    bucket-name: YOUR_VALUE