imports:
- path: twitter-aggregator.jinja
  name: twitter-aggregator.jinja

resources:
- name: twitter-aggregator
  type: twitter-aggregator.jinja
  properties:
    description: "YOUR_VALUE"
    project-name: twitter-aggregator-fedex-kp #YOUR_VALUE
    bucket-name: twitter-aggregator-fedex-bucket-kp #YOUR_VALUE
    TWITTER_API_KEY: YOUR_VALUE
    TWITTER_API_SECRET_KEY: YOUR_VALUE
    TWITTER_ACCESS_TOKEN: YOUR_VALUE
    TWITTER_ACCESS_TOKEN_SECRET: YOUR_VALUE
    COUNTRY: Netherlands
    DATE_SINCE: YOUR_VALUE_IN_FORMAT_202103250000